package studentinfo.connectionH2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class H2DatabaseConnection {

    static {
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    private static final String DATABASE_URL = "jdbc:h2:~/test"; // http://localhost:8082

    private static final String USER = "sa";
    private static final String PASSWORD = "1234";

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DATABASE_URL, USER, PASSWORD);
    }
    
    public static void applySchema() {
        try (Connection connection = getConnection()) {
            Statement schema = connection.createStatement();
            schema.executeUpdate("CREATE TABLE IF NOT EXISTS Groups(" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "name VARCHAR(200) UNIQUE);");

            schema.executeUpdate("CREATE TABLE IF NOT EXISTS Students(" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "name VARCHAR(200) UNIQUE," +
                    "group_id VARCHAR(200)," +
                    "address VARCHAR(200)," +
                    "city VARCHAR(200)," +
                    "result INT," +
                    "image BLOB," +
                    "FOREIGN KEY(group_id) REFERENCES Groups(id));");

            schema.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void closeConnection(Connection connection) {
        if (connection != null) {
            try {
                Statement statement = connection.createStatement();
                statement.execute("SHUTDOWN COMPACT");
                statement.close();
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
